name: Label-Based Task ID Prefixer

on:
  issues:
    types: [opened, labeled]

jobs:
  add-prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Set task prefix based on label
        run: |
          ISSUE_TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          LABEL=$(jq -r '.issue.labels[0].name' "$GITHUB_EVENT_PATH")

          case "$LABEL" in
            "Bug")
              PREFIX="BUG"
              ;;
            "Feature")
              PREFIX="FEATURE"
              ;;
            "Improvement")
              PREFIX="IMPROVEMENT"
              ;;
            "Refactor")
              PREFIX="REFACTOR"
              ;;
            *)
              PREFIX="TASK"
              ;;
          esac

          NEW_TITLE="${PREFIX}-${ISSUE_NUMBER}: ${ISSUE_TITLE}"

          # Update issue title
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} \
            -d "{\"title\":\"${NEW_TITLE}\"}"
