name: Assign Task ID based on Label

on:
  issues:
    types: [opened, labeled]

jobs:
  assign_task_id:
    runs-on: ubuntu-latest
    steps:
    - name: Get issue labels
      id: issue
      uses: actions/github-issue-labels@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check and assign task ID
      run: |
        labels=$(echo "${{ steps.issue.outputs.labels }}")
        echo "Labels: $labels"
        issue_number=${{ github.event.issue.number }}
        issue_title="${{ github.event.issue.title }}"
        repo_owner="${{ github.repository_owner }}"
        repo_name="${{ github.event.repository.name }}"

        prefix=""

        case "$labels" in
          *Frontend\ Backlog*)
            prefix="FB"
            ;;
          *Backend\ Backlog*)
            prefix="BB"
            ;;
          *Devops\ Request*)
            prefix="DR"
            ;;
          *Design\ Backlog*)
            prefix="DB"
            ;;
          *Software\ Bug*)
            prefix="SB"
            ;;
        esac

        if [ -z "$prefix" ]; then
          echo "No matching label found. Exiting."
          exit 0
        fi

        task_id="${prefix}-$(printf "%03d" $issue_number)"

        # Add the task ID as a comment
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${repo_owner}/${repo_name}/issues/${issue_number}/comments \
          -d "{\"body\": \"Task ID: ${task_id}\"}"

        # Update the issue title to include the task ID
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${repo_owner}/${repo_name}/issues/${issue_number} \
          -d "{\"title\": \"${task_id}: ${issue_title}\"}"
